name: CI
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint
